import {
  Client,
  ClientService,
  Plan,
  NodeLocation,
  IpPool,
  ArcotelPolicy,
  VaultCredential,
  Ticket,
  Expense,
  MonthlyCharge,
  UserProfile,
} from "@/types";

export interface SystemAccount {
  user: UserProfile;
  passwordHash: string; // pre-configured demo passwords
}

export const SYSTEM_ACCOUNTS: SystemAccount[] = [
  {
    user: {
      uid: "usr-admin-01",
      email: "admin@inntelcorp.ec",
      displayName: "Ing. Santiago Morales",
      role: "admin",
      department: "NOC Central & Gerencia General",
      phone: "+593 99 876 5432",
    },
    passwordHash: "Admin2026*",
  },
  {
    user: {
      uid: "usr-fin-02",
      email: "finanzas@inntelcorp.ec",
      displayName: "Lcda. Patricia Andrade",
      role: "finanzas",
      department: "Contabilidad & Facturación SRI",
      phone: "+593 98 432 1098",
    },
    passwordHash: "Finanzas2026*",
  },
  {
    user: {
      uid: "usr-tec-03",
      email: "tecnico@inntelcorp.ec",
      displayName: "Ing. Carlos Benítez",
      role: "tecnico",
      department: "Ingeniería NOC & MikroTik",
      phone: "+593 97 123 4567",
    },
    passwordHash: "Tecnico2026*",
  },
  {
    user: {
      uid: "usr-sop-04",
      email: "soporte@inntelcorp.ec",
      displayName: "Téc. Alex Mendoza",
      role: "soporte",
      department: "Mesa de Ayuda & Cuadrillas",
      phone: "+593 96 987 6543",
    },
    passwordHash: "Soporte2026*",
  },
  {
    user: {
      uid: "usr-leg-05",
      email: "legal@inntelcorp.ec",
      displayName: "Abg. Fernando Viteri",
      role: "consulta",
      department: "Asesoría Legal & ARCOTEL",
      phone: "+593 95 654 3210",
    },
    passwordHash: "Arcotel2026*",
  },
];

export const INITIAL_USER: UserProfile = SYSTEM_ACCOUNTS[0].user;

export const INITIAL_PLANS: Plan[] = [
  {
    id: "plan-50m",
    name: "Fibra Óptica Residencial 50M",
    downloadMbps: 50,
    uploadMbps: 50,
    defaultPrice: 20.0,
    billingType: "pospago",
    description: "Internet simétrico residencial de alta velocidad",
  },
  {
    id: "plan-100m",
    name: "Fibra Óptica Hogar & PYME 100M",
    downloadMbps: 100,
    uploadMbps: 100,
    defaultPrice: 28.0,
    billingType: "pospago",
    description: "Plan recomendado con IP pública dinámica y baja latencia",
  },
  {
    id: "plan-200m",
    name: "Fibra Óptica Corporativo 200M",
    downloadMbps: 200,
    uploadMbps: 200,
    defaultPrice: 45.0,
    billingType: "pospago",
    description: "Enlace simétrico para empresas con SLA garantizado",
  },
  {
    id: "plan-500m",
    name: "Fibra Óptica Dedicado 500M",
    downloadMbps: 500,
    uploadMbps: 500,
    defaultPrice: 95.0,
    billingType: "pospago",
    description: "Canal dedicado 1:1 con pool de IPs estáticas /29",
  },
];

export const INITIAL_NODES: NodeLocation[] = [
  {
    id: "nodo-1",
    name: "POP Central Matriz (Quito Norte)",
    address: "Av. 10 de Agosto N34-12 y Mariana de Jesús, Torre Panecillo",
    upstreamProvider: "Telconet Latam (10 Gbps BGP)",
    totalCapacityMbps: 5000,
    usedCapacityMbps: 2840,
    mikrotikIp: "10.50.0.1",
    status: "online",
    activeClientsCount: 420,
    notes: "Core Router CCR2116-12G-4S+ redundante con BGP y OSPF",
  },
  {
    id: "nodo-2",
    name: "POP Sur - Villaflora",
    address: "Av. Rodrigo de Chávez y 5 de Junio",
    upstreamProvider: "CenturyLink / Lumen (5 Gbps)",
    totalCapacityMbps: 3000,
    usedCapacityMbps: 1950,
    mikrotikIp: "10.50.1.1",
    status: "online",
    activeClientsCount: 280,
    notes: "Concentrador PPPoE CCR1036 y OLT Huawei MA5800",
  },
  {
    id: "nodo-3",
    name: "POP Valle de los Chillos",
    address: "Av. General Rumiñahui e Ilaló, San Rafael",
    upstreamProvider: "Telconet Latam (5 Gbps)",
    totalCapacityMbps: 4000,
    usedCapacityMbps: 2410,
    mikrotikIp: "10.50.2.1",
    status: "online",
    activeClientsCount: 340,
    notes: "Anillo de fibra óptica redundante con tecnología DWDM",
  },
  {
    id: "nodo-4",
    name: "POP Calderón / Carapungo",
    address: "Av. Giovanni Calles y Panamericana Norte",
    upstreamProvider: "Ufinet (3 Gbps)",
    totalCapacityMbps: 2000,
    usedCapacityMbps: 1650,
    mikrotikIp: "10.50.3.1",
    status: "warning",
    activeClientsCount: 190,
    notes: "Utilización superior al 80%. Programada ampliación a 5 Gbps",
  },
];

export const INITIAL_IP_POOLS: IpPool[] = [
  {
    id: "pool-cgnat-1",
    name: "Pool CGNAT Clientes Residenciales Norte",
    subnetCidr: "100.64.0.0/20",
    gateway: "100.64.0.1",
    type: "cgnat",
    totalIpsCount: 4096,
    usableIpsCount: 4094,
    assignedIpsCount: 2840,
    nodeId: "nodo-1",
  },
  {
    id: "pool-cgnat-2",
    name: "Pool CGNAT Sur y Valles",
    subnetCidr: "100.64.16.0/20",
    gateway: "100.64.16.1",
    type: "cgnat",
    totalIpsCount: 4096,
    usableIpsCount: 4094,
    assignedIpsCount: 2410,
    nodeId: "nodo-2",
  },
  {
    id: "pool-pub-corp",
    name: "Pool IPs Públicas Estáticas ARIN / LACNIC",
    subnetCidr: "186.46.120.0/24",
    gateway: "186.46.120.1",
    type: "publica_fija",
    totalIpsCount: 256,
    usableIpsCount: 254,
    assignedIpsCount: 182,
    nodeId: "nodo-1",
  },
  {
    id: "pool-ipv6-prefix",
    name: "Prefijos IPv6 /48 para Abonados SAI",
    subnetCidr: "2800:3a0:100::/48",
    gateway: "2800:3a0:100::1",
    type: "ipv6_pool",
    totalIpsCount: 65536,
    usableIpsCount: 65535,
    assignedIpsCount: 1230,
    nodeId: "nodo-1",
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: "cli-001",
    identificationType: "RUC",
    identificationNumber: "1792841092001",
    businessName: "DISTRIBUIDORA FARMACEUTICA ANDINA S.A.",
    legalRepresentative: "Dr. Carlos Enrique Dávila",
    email: "facturacion@farmandina.com.ec",
    phone: "022485900 / 0998412354",
    address: "Av. República de El Salvador N34-123 y Moscú, Edificio Alianza",
    sector: "Quito Norte",
    requiresSriBilling: true,
    status: "activo",
    totalActiveServices: 2,
    currentBalance: 0.0,
    createdAt: "2024-03-15T10:00:00Z",
    updatedAt: "2026-08-10T14:30:00Z",
  },
  {
    id: "cli-002",
    identificationType: "CEDULA",
    identificationNumber: "1718293041",
    businessName: "MARÍA FERNANDA VALLEJO ESPINOSA",
    email: "mafe.vallejo@gmail.com",
    phone: "0987654321",
    address: "Calle Los Guabos 142 y Av. Ilaló, San Rafael",
    sector: "Valle de los Chillos",
    requiresSriBilling: false,
    status: "activo",
    totalActiveServices: 1,
    currentBalance: 28.0,
    createdAt: "2024-06-20T11:20:00Z",
    updatedAt: "2026-08-01T09:15:00Z",
  },
  {
    id: "cli-003",
    identificationType: "RUC",
    identificationNumber: "1793184920001",
    businessName: "CONSTRUCTORA & DISENO URBANO QUITO CIA. LTDA.",
    legalRepresentative: "Arq. Roberto Guarderas",
    email: "administracion@constructoraurbana.ec",
    phone: "023948500",
    address: "Av. Shyris N39-20 y El Telégrafo",
    sector: "Quito Norte",
    requiresSriBilling: true,
    status: "activo",
    totalActiveServices: 1,
    currentBalance: 0.0,
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2026-07-28T16:00:00Z",
  },
  {
    id: "cli-004",
    identificationType: "CEDULA",
    identificationNumber: "1720491823",
    businessName: "JUAN SEBASTIÁN PROAÑO MORA",
    email: "juan.proano@hotmail.com",
    phone: "0991238475",
    address: "Av. Rodrigo de Chávez OE4-55 y 5 de Junio",
    sector: "Quito Sur",
    requiresSriBilling: false,
    status: "suspendido",
    totalActiveServices: 1,
    currentBalance: 56.0,
    createdAt: "2025-04-12T14:40:00Z",
    updatedAt: "2026-08-20T10:00:00Z",
  },
];

export const INITIAL_CLIENT_SERVICES: ClientService[] = [
  {
    id: "srv-001",
    clientId: "cli-001",
    planId: "plan-500m",
    planName: "Fibra Óptica Dedicado 500M",
    downloadMbps: 500,
    uploadMbps: 500,
    basePrice: 95.0,
    customPrice: 90.0,
    billingType: "pospago",
    cutoffDay: 1,
    nodeId: "nodo-1",
    nodeName: "POP Central Matriz (Quito Norte)",
    ipv4Address: "186.46.120.14",
    pppoeUser: "farmandina_corp",
    status: "activo",
    installationDate: "2024-03-16",
  },
  {
    id: "srv-002",
    clientId: "cli-001",
    planId: "plan-200m",
    planName: "Fibra Óptica Corporativo 200M (Sucursal Sur)",
    downloadMbps: 200,
    uploadMbps: 200,
    basePrice: 45.0,
    customPrice: 40.0,
    billingType: "pospago",
    cutoffDay: 1,
    nodeId: "nodo-2",
    nodeName: "POP Sur - Villaflora",
    ipv4Address: "186.46.120.25",
    pppoeUser: "farmandina_sur",
    status: "activo",
    installationDate: "2024-04-01",
  },
  {
    id: "srv-003",
    clientId: "cli-002",
    planId: "plan-100m",
    planName: "Fibra Óptica Hogar & PYME 100M",
    downloadMbps: 100,
    uploadMbps: 100,
    basePrice: 28.0,
    customPrice: 28.0,
    billingType: "pospago",
    cutoffDay: 1,
    nodeId: "nodo-3",
    nodeName: "POP Valle de los Chillos",
    ipv4Address: "100.64.18.94",
    pppoeUser: "1718293041",
    status: "activo",
    installationDate: "2024-06-22",
  },
  {
    id: "srv-004",
    clientId: "cli-003",
    planId: "plan-200m",
    planName: "Fibra Óptica Corporativo 200M",
    downloadMbps: 200,
    uploadMbps: 200,
    basePrice: 45.0,
    customPrice: 45.0,
    billingType: "pospago",
    cutoffDay: 1,
    nodeId: "nodo-1",
    nodeName: "POP Central Matriz (Quito Norte)",
    ipv4Address: "186.46.120.55",
    pppoeUser: "constructora_urb",
    status: "activo",
    installationDate: "2025-01-12",
  },
  {
    id: "srv-005",
    clientId: "cli-004",
    planId: "plan-100m",
    planName: "Fibra Óptica Hogar & PYME 100M",
    downloadMbps: 100,
    uploadMbps: 100,
    basePrice: 28.0,
    customPrice: 28.0,
    billingType: "pospago",
    cutoffDay: 1,
    nodeId: "nodo-2",
    nodeName: "POP Sur - Villaflora",
    ipv4Address: "100.64.20.12",
    pppoeUser: "1720491823",
    status: "suspendido",
    installationDate: "2025-04-15",
  },
];

export const INITIAL_POLICIES: ArcotelPolicy[] = [
  {
    id: "pol-001",
    policyNumber: "POL-SUCRE-2025-00984",
    insuranceCompany: "Seguros Sucre S.A. / La Unión",
    policyType: "fiel_cumplimiento",
    titleGrantCode: "ARCOTEL-TH-ISP-2018-094",
    startDate: "2025-10-15",
    expirationDate: "2026-10-15",
    insuredAmount: 25000.0,
    status: "vigente",
    daysUntilExpiration: 45,
    notes: "Póliza de Fiel Cumplimiento del Título Habilitante para Servicio de Internet SAI.",
  },
  {
    id: "pol-002",
    policyNumber: "POL-CHUBB-2025-88412",
    insuranceCompany: "Chubb Seguros Ecuador S.A.",
    policyType: "responsabilidad_civil",
    titleGrantCode: "ARCOTEL-TH-ISP-2018-094",
    startDate: "2025-09-20",
    expirationDate: "2026-09-20",
    insuredAmount: 50000.0,
    status: "por_vencer",
    daysUntilExpiration: 20,
    notes: "ALERTA URGENTE: Renovar antes del 20 de Septiembre para evitar sanción pecuniaria ARCOTEL.",
  },
  {
    id: "pol-003",
    policyNumber: "POL-ALIANZA-2024-11234",
    insuranceCompany: "Seguros Alianza",
    policyType: "buen_uso_anticipo",
    titleGrantCode: "CONTRATO-EPMMOP-FIBRA-2024",
    startDate: "2024-08-01",
    expirationDate: "2025-08-01",
    insuredAmount: 15000.0,
    status: "vencida",
    daysUntilExpiration: -395,
    notes: "Póliza finiquitada y devuelta con acta de entrega recepción definitiva.",
  },
];

export const INITIAL_VAULT: VaultCredential[] = [
  {
    id: "vlt-001",
    serviceName: "Portal SIETEL ARCOTEL (Reporte Estadístico)",
    serviceType: "sietel",
    portalUrl: "https://sietel.arcotel.gob.ec/sietel-web",
    username: "inntel_corp_rep",
    encryptedPassword: "ENC_U2FsdGVkX19aVm1qS0xROXN1cGVyc2VjdXJlMTIz",
    notes: "Carga mensual de abonados SAI hasta el día 15 de cada mes.",
    allowedRoles: ["admin", "finanzas"],
    lastAccessedAt: "2026-08-14T16:20:00Z",
    updatedAt: "2026-01-10T10:00:00Z",
  },
  {
    id: "vlt-002",
    serviceName: "FODETEL - Fondo de Telecomunicaciones",
    serviceType: "fodetel",
    portalUrl: "https://fodetel.arcotel.gob.ec/login",
    username: "inntel_fodetel_2026",
    encryptedPassword: "ENC_U2FsdGVkX19GMGRIZWwwV0AxMjMhI0RvbmU=",
    notes: "Declaración del 1% de ingresos facturados para el fondo universal.",
    allowedRoles: ["admin", "finanzas"],
    lastAccessedAt: "2026-08-10T11:00:00Z",
    updatedAt: "2026-02-15T09:30:00Z",
  },
  {
    id: "vlt-003",
    serviceName: "QUIPUX - Sistema de Gestión Documental del Estado",
    serviceType: "quipux",
    portalUrl: "https://www.gestiondocumental.gob.ec",
    username: "santiago.morales.inntel",
    encryptedPassword: "ENC_U2FsdGVkX19RdWlwdXhQYXNzV29yZDIwMjY=",
    notes: "Ingreso de oficios de renovación de pólizas y respuestas a notificaciones ARCOTEL.",
    allowedRoles: ["admin"],
    lastAccessedAt: "2026-08-25T14:10:00Z",
    updatedAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "vlt-004",
    serviceName: "Base de Datos de Abonados Sujetos a Control (BDH / MIES)",
    serviceType: "bdh",
    portalUrl: "https://servicios.inclusion.gob.ec/bdh-consulta",
    username: "consultas_inntel_bdh",
    encryptedPassword: "ENC_U2FsdGVkX19CREhDb25zdWx0YTIwMjZTZWN1cmU=",
    notes: "Validación de tarifas sociales preferenciales para beneficiarios de bonos.",
    allowedRoles: ["admin", "finanzas", "soporte"],
    lastAccessedAt: "2026-08-28T09:45:00Z",
    updatedAt: "2026-04-10T12:00:00Z",
  },
  {
    id: "vlt-005",
    serviceName: "MikroTik Core Router Master (CCR2116 - POP Matriz)",
    serviceType: "mikrotik",
    portalUrl: "10.50.0.1:8291",
    username: "noc_master_admin",
    encryptedPassword: "ENC_U2FsdGVkX19NaWtyb1Rpa0FkbWluMjAyNiFRdWl0bw==",
    notes: "Acceso SSH / Winbox con autenticación por llave y firewall restrictivo.",
    allowedRoles: ["admin", "tecnico"],
    lastAccessedAt: "2026-08-30T17:40:00Z",
    updatedAt: "2026-07-01T15:00:00Z",
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: "tck-001",
    ticketNumber: "TCK-1081",
    clientId: "cli-004",
    clientName: "JUAN SEBASTIÁN PROAÑO MORA",
    title: "Corte de fibra por caída de árbol en Villaflora",
    description: "Cliente reporta LOS rojo en la ONT Huawei. Se requiere cuadrilla de empalme y reflectometría OTDR.",
    category: "corte_fibra",
    priority: "alta",
    status: "en_progreso",
    assignedToName: "Téc. Roberto Guallasamín (Cuadrilla Sur)",
    createdAt: "2026-08-30T14:30:00Z",
    nodeName: "POP Sur - Villaflora",
  },
  {
    id: "tck-002",
    ticketNumber: "TCK-1082",
    clientId: "cli-001",
    clientName: "DISTRIBUIDORA FARMACEUTICA ANDINA S.A.",
    title: "Solicitud de direccionamiento IP fija /29 adicional",
    description: "Ampliación de servicios para nuevo servidor VPN institucional de Farmandina.",
    category: "configuracion_ip",
    priority: "media",
    status: "resuelto",
    assignedToName: "Ing. Santiago Morales (NOC Central)",
    createdAt: "2026-08-28T09:15:00Z",
    resolvedAt: "2026-08-28T16:00:00Z",
    resolutionNotes: "Se asignó pool /29 (186.46.120.32/29) en el RouterOS con rutas estáticas hacia el cliente.",
    nodeName: "POP Central Matriz (Quito Norte)",
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: "exp-001",
    supplierName: "Telconet Latam S.A.",
    category: "enlace_transito",
    amount: 1450.0,
    description: "Tránsito IP Internacional 10 Gbps BGP y transporte interurbano (Factura 001-100-98412)",
    expenseDate: "2026-08-05",
    paymentMethod: "transferencia",
    invoiceNumber: "001-100-0098412",
  },
  {
    id: "exp-002",
    supplierName: "Torrecuador Infraestructura Cía. Ltda.",
    category: "alquiler_nodo",
    amount: 650.0,
    description: "Arriendo de espacio en caseta y torre para POP Panecillo y Villaflora",
    expenseDate: "2026-08-08",
    paymentMethod: "transferencia",
    invoiceNumber: "002-200-0014298",
  },
  {
    id: "exp-003",
    supplierName: "OptiCom Ecuador - Cables & Conectividad",
    category: "fibra_equipos",
    amount: 820.0,
    description: "Compra de 4 bobinas de cable drop de 1 hilo G.657A2 y 50 conectores mecánicos SC/APC",
    expenseDate: "2026-08-12",
    paymentMethod: "tarjeta_credito",
    invoiceNumber: "001-005-0004812",
  },
];

export const INITIAL_MONTHLY_CHARGES: MonthlyCharge[] = [
  {
    id: "chg-001",
    clientId: "cli-001",
    clientName: "DISTRIBUIDORA FARMACEUTICA ANDINA S.A.",
    clientRuc: "1792841092001",
    month: 8,
    year: 2026,
    serviceDescription: "Servicio Dedicado 500M + Enlace Corporativo 200M (Periodo Agosto 2026)",
    subtotal: 113.04,
    ivaAmount: 16.96,
    total: 130.0,
    status: "pagado",
    paymentDate: "2026-08-04",
    paymentMethod: "Transferencia Banco Pichincha",
    invoiceNumber: "001-100-0004891",
  },
  {
    id: "chg-002",
    clientId: "cli-002",
    clientName: "MARÍA FERNANDA VALLEJO ESPINOSA",
    clientRuc: "1718293041",
    month: 8,
    year: 2026,
    serviceDescription: "Plan Fibra Óptica Hogar 100M (Periodo Agosto 2026)",
    subtotal: 24.35,
    ivaAmount: 3.65,
    total: 28.0,
    status: "pendiente",
    invoiceNumber: "001-100-0004892",
  },
  {
    id: "chg-003",
    clientId: "cli-003",
    clientName: "CONSTRUCTORA & DISENO URBANO QUITO CIA. LTDA.",
    clientRuc: "1793184920001",
    month: 8,
    year: 2026,
    serviceDescription: "Plan Corporativo 200M (Periodo Agosto 2026)",
    subtotal: 39.13,
    ivaAmount: 5.87,
    total: 45.0,
    status: "pagado",
    paymentDate: "2026-08-02",
    paymentMethod: "Transferencia Banco Guayaquil",
    invoiceNumber: "001-100-0004893",
  },
];
