import {
  Client,
  ClientService,
  Plan,
  NodeLocation,
  IpPool,
  ArcotelPolicy,
  VaultCredential,
  Ticket,
  Expense,
  MonthlyCharge,
  UserProfile,
  SystemUser,
  ClientProjectTask,
  ClientQuoteOrder,
  ClientVaultItem,
  ClientContractInfo,
  AuditLog,
  ArcotelConcessionInfo,
  ArcotelPeriodicFile,
  ClientDocumentFile,
  InventoryProduct,
  Warehouse,
  ProductCategory,
  ProductBrand,
  KardexEntry,
  WarehouseTransfer,
  InventoryAdjustment,
} from "@/types";
import { simpleEncrypt } from "./crypto-vault";

export const INITIAL_SYSTEM_USERS: SystemUser[] = [
  {
    uid: "usr-superadmin-00",
    email: "superadmin@inntelcorp.com",
    displayName: "Ing. Santiago Morales",
    role: "superadmin",
    department: "Presidencia Ejecutiva & NOC Central",
    phone: "+593 99 876 5432",
    status: "activo",
    passwordHash: "SuperAdmin2026*",
    permissions: [
      "all",
      "manage_users",
      "manage_vault",
      "manage_clients",
      "manage_network",
      "manage_tickets",
      "manage_finance",
      "manage_policies",
      "export_reports",
    ],
    createdAt: "2024-01-01T08:00:00Z",
  },
  {
    uid: "usr-admin-01",
    email: "admin@inntelcorp.com",
    displayName: "Ing. Diego Cárdenas",
    role: "admin",
    department: "Gerencia de Operaciones",
    phone: "+593 99 111 2233",
    status: "activo",
    passwordHash: "Admin2026*",
    permissions: [
      "manage_vault",
      "manage_clients",
      "manage_network",
      "manage_tickets",
      "manage_finance",
      "manage_policies",
      "export_reports",
    ],
    createdAt: "2024-02-15T09:30:00Z",
  },
  {
    uid: "usr-fin-02",
    email: "finanzas@inntelcorp.com",
    displayName: "Lcda. Patricia Andrade",
    role: "finanzas",
    department: "Contabilidad & Cobranzas",
    phone: "+593 98 432 1098",
    status: "activo",
    passwordHash: "Finanzas2026*",
    permissions: ["manage_finance", "manage_clients", "export_reports"],
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    uid: "usr-tec-03",
    email: "tecnico@inntelcorp.com",
    displayName: "Ing. Carlos Benítez",
    role: "tecnico",
    department: "Ingeniería NOC & MikroTik",
    phone: "+593 97 123 4567",
    status: "activo",
    passwordHash: "Tecnico2026*",
    permissions: ["manage_network", "manage_tickets", "manage_clients"],
    createdAt: "2024-03-10T11:15:00Z",
  },
  {
    uid: "usr-sop-04",
    email: "soporte@inntelcorp.com",
    displayName: "Téc. Alex Mendoza",
    role: "soporte",
    department: "Mesa de Ayuda & Cuadrillas",
    phone: "+593 96 987 6543",
    status: "activo",
    passwordHash: "Soporte2026*",
    permissions: ["manage_tickets"],
    createdAt: "2024-04-05T08:45:00Z",
  },
  {
    uid: "usr-leg-05",
    email: "legal@inntelcorp.com",
    displayName: "Abg. Fernando Viteri",
    role: "legal",
    department: "Asesoría Jurídica & ARCOTEL",
    phone: "+593 95 654 3210",
    status: "activo",
    passwordHash: "Arcotel2026*",
    permissions: ["manage_policies", "export_reports"],
    createdAt: "2024-04-20T14:00:00Z",
  },
];

export interface SystemAccount {
  user: UserProfile;
  passwordHash: string;
}

export const SYSTEM_ACCOUNTS: SystemAccount[] = INITIAL_SYSTEM_USERS.map((u) => ({
  user: {
    uid: u.uid,
    email: u.email,
    displayName: u.displayName,
    role: u.role,
    department: u.department,
    phone: u.phone,
    status: u.status,
    permissions: u.permissions,
  },
  passwordHash: u.passwordHash,
}));

export const INITIAL_USER: UserProfile = INITIAL_SYSTEM_USERS[0];

export const INITIAL_PLANS: Plan[] = [
  {
    id: "plan-50m",
    name: "Fibra Óptica Residencial 50M",
    downloadMbps: 50,
    uploadMbps: 50,
    defaultPrice: 20.0,
    billingType: "pospago",
    description: "Internet simétrico residencial de alta velocidad",
  },
  {
    id: "plan-100m",
    name: "Fibra Óptica Hogar & PYME 100M",
    downloadMbps: 100,
    uploadMbps: 100,
    defaultPrice: 28.0,
    billingType: "pospago",
    description: "Plan recomendado con IP pública dinámica y baja latencia",
  },
  {
    id: "plan-200m",
    name: "Fibra Óptica Corporativo 200M",
    downloadMbps: 200,
    uploadMbps: 200,
    defaultPrice: 45.0,
    billingType: "pospago",
    description: "Enlace simétrico para empresas con SLA garantizado",
  },
  {
    id: "plan-500m",
    name: "Fibra Óptica Dedicado 500M",
    downloadMbps: 500,
    uploadMbps: 500,
    defaultPrice: 95.0,
    billingType: "pospago",
    description: "Canal dedicado 1:1 con pool de IPs estáticas /29",
  },
];

// ============================================================================
// CLIENTE DEMO 360° CON PROCESO OPERATIVO COMPLETO (END-TO-END)
// ============================================================================

export const DEMO_CLIENT: Client = {
  id: "cli-demo-corp-01",
  identificationType: "RUC",
  identificationNumber: "1792345678001",
  businessName: "CORPORACIÓN INDUSTRIAL Y LOGÍSTICA ECUATORIANA C.A.",
  legalRepresentative: "Ing. Patricio Echeverría",
  email: "gerencia@corpecuador.com",
  phone: "+593 2 298 7654",
  address: "Av. República de El Salvador N36-140 y Naciones Unidas, Edificio Platinum Plaza, Piso 8, Quito",
  sector: "Quito Norte - Distrito Financiero",
  requiresSriBilling: true,
  status: "activo",
  totalActiveServices: 1,
  currentBalance: 109.25,
  createdAt: "2024-01-15T08:00:00Z",
  updatedAt: "2026-09-18T10:00:00Z",
  contactName: "Ing. Patricio Echeverría",
  contactRole: "Director de Operaciones & IT",
  contactPhone: "0998451234",
  contactAddress: "Av. República de El Salvador N36-140, Quito",
};

export const DEMO_NODE: NodeLocation = {
  id: "nodo-quito-norte",
  clientId: "cli-demo-corp-01",
  clientName: "CORPORACIÓN INDUSTRIAL Y LOGÍSTICA ECUATORIANA C.A.",
  name: "Sede Principal - Centro Corporativo Quito Norte",
  province: "Pichincha",
  canton: "Quito",
  parish: "Iñaquito",
  detailedAddress: "Av. 6 de Diciembre N34-120 y Eloy Alfaro, Edificio Platinum Plaza Piso 8",
  address: "Av. 6 de Diciembre N34-120 y Eloy Alfaro, Iñaquito, Quito, Pichincha",
  coordinates: { lat: -0.180653, lng: -78.484215 },
  upstreamProvider: "Telconet / CenturyLink / Ufinet",
  totalCapacityMbps: 10000,
  usedCapacityMbps: 2450,
  mikrotikIp: "10.200.1.1",
  status: "online",
  activeClientsCount: 1,
  notes: "Router de borde MikroTik CCR2004 con RouterOS v7 y BGP peering multi-carrier entregado por el cliente.",
  providers: [
    {
      id: "prov-1",
      providerName: "Telconet Latam",
      capacityMbps: 5000,
      circuitId: "TCO-UIO-9921",
      ipv4Subnet: "181.198.112.112/30",
      ipv6Prefix: "2800:3f0:4000::/48",
    },
    {
      id: "prov-2",
      providerName: "CenturyLink / Lumen",
      capacityMbps: 3000,
      circuitId: "LMN-EC-4412",
      ipv4Subnet: "190.152.88.24/30",
      ipv6Prefix: "2800:3f0:4001::/48",
    },
    {
      id: "prov-3",
      providerName: "Ufinet Telecom",
      capacityMbps: 2000,
      circuitId: "UFI-INTEL-08",
      ipv4Subnet: "186.42.110.1/30",
      ipv6Prefix: "2800:3f0:4002::/48",
    },
  ],
  services: [
    {
      id: "srv-sys-1",
      systemName: "MIKROTIK CCR2116-12G-4S+",
      linkOrIp: "181.198.112.112:5258",
      credentials: "admin / InntelRouter2026*",
      notes: "Core BGP Router & CGNAT Sede Norte",
    },
    {
      id: "srv-sys-2",
      systemName: "SMART OLT",
      linkOrIp: "https://sotelnet.smartolt.com/auth/login",
      credentials: "noc@inntelcorp.com / OltPlatform2026*",
      notes: "Plataforma de aprovisionamiento de ONUs",
    },
  ],
};

export const DEMO_NODE_2: NodeLocation = {
  id: "nodo-guayaquil-pto",
  clientId: "cli-demo-corp-01",
  clientName: "CORPORACIÓN INDUSTRIAL Y LOGÍSTICA ECUATORIANA C.A.",
  name: "Sucursal Operativa - Puerto Marítimo Guayaquil",
  province: "Guayas",
  canton: "Guayaquil",
  parish: "Tarqui",
  detailedAddress: "Av. Carlos Julio Arosemena Km 3.5, Bodegas Centrales Muelle 4",
  address: "Av. Carlos Julio Arosemena Km 3.5, Tarqui, Guayaquil, Guayas",
  coordinates: { lat: -2.189412, lng: -79.889066 },
  upstreamProvider: "Telconet / PuntoNet",
  totalCapacityMbps: 2000,
  usedCapacityMbps: 850,
  mikrotikIp: "10.200.2.1",
  status: "online",
  activeClientsCount: 1,
  notes: "Enlace punto a punto redundante para control logístico aduanero y cámaras de seguridad.",
  providers: [
    {
      id: "prov-gye-1",
      providerName: "Telconet Latam",
      capacityMbps: 1000,
      circuitId: "TCO-GYE-7731",
      ipv4Subnet: "181.198.120.4/30",
      ipv6Prefix: "2800:3f0:5000::/48",
    },
    {
      id: "prov-gye-2",
      providerName: "PuntoNet Fibra",
      capacityMbps: 1000,
      circuitId: "PNT-GYE-209",
      ipv4Subnet: "190.152.95.8/30",
      ipv6Prefix: "2800:3f0:5001::/48",
    },
  ],
  services: [
    {
      id: "srv-sys-gye",
      systemName: "MikroTik RB5009UG+S+IN",
      linkOrIp: "181.198.120.4:8291",
      credentials: "admin / GyeLogistica2026*",
      notes: "Firewall & VPN Túnel IPsec con Matriz Quito",
    },
  ],
};

export const DEMO_IP_POOL: IpPool = {
  id: "pool-corp-public",
  name: "Pool Corporativo IPs Públicas Fijas /28 (ARCOTEL)",
  subnetCidr: "186.42.110.0/28",
  gateway: "186.42.110.1",
  type: "publica_fija",
  totalIpsCount: 16,
  usableIpsCount: 14,
  assignedIpsCount: 1,
  nodeId: "nodo-quito-norte",
};

export const DEMO_CLIENT_SERVICE: ClientService = {
  id: "srv-demo-01",
  clientId: "cli-demo-corp-01",
  planId: "plan-500m",
  planName: "Fibra Óptica Dedicado 500M",
  downloadMbps: 500,
  uploadMbps: 500,
  basePrice: 95.0,
  customPrice: 95.0,
  billingType: "pospago",
  cutoffDay: 1,
  nodeId: "nodo-quito-norte",
  nodeName: "POP 01 - Telepuerto Quito Norte (MikroTik CCR2004)",
  ipv4Address: "186.42.110.5",
  ipv6Prefix: "2800:3f0:4000:100::/64",
  pppoeUser: "corpecuador_corp",
  pppoePassword: "CorpSecurePppoe2026*",
  status: "activo",
  installationDate: "2024-01-20",
  installationAddress: "Av. República de El Salvador N36-140 y Naciones Unidas, Edificio Platinum Plaza, Piso 8, Quito",
  coordinates: { lat: -0.179854, lng: -78.483214 },
  ontSerialNumber: "HWTCD928B104",
  notes: "Enlace simétrico 1:1 corporativo. Pigtail monomodo LC-APC con OLT Huawei SmartAX y ONU Huawei EchoLife.",
};

export const DEMO_QUOTE_ORDER: ClientQuoteOrder = {
  id: "ord-2024-001",
  clientId: "cli-demo-corp-01",
  clientName: "CORPORACIÓN INDUSTRIAL Y LOGÍSTICA ECUATORIANA C.A.",
  clientRuc: "1792345678001",
  quoteNumber: "COT-2024-0089",
  title: "Orden de Pedido: Conectividad Fibra Óptica 500M Simétrica + Router Wi-Fi 6 Corporativo",
  items: [
    {
      id: "itm-01",
      description: "Acometida e Instalación Fibra Óptica Monomodo 2 Hilos (150m)",
      quantity: 1,
      unitPrice: 120.0,
      total: 120.0,
    },
    {
      id: "itm-02",
      description: "Router de Borde MikroTik hEX S + ONU GPON Huawei EchoLife",
      quantity: 1,
      unitPrice: 150.0,
      total: 150.0,
    },
    {
      id: "itm-03",
      description: "Mensualidad Plan Dedicado 500 Mbps Simétrico (Mes de Inicio)",
      quantity: 1,
      unitPrice: 95.0,
      total: 95.0,
    },
  ],
  subtotal: 365.0,
  ivaAmount: 54.75,
  total: 419.75,
  status: "facturada",
  validUntil: "2024-02-15",
  notes: "Aprobado por Gerencia General. Cumple especificaciones técnicas ARCOTEL.",
  createdAt: "2024-01-16T10:30:00Z",
};

export const DEMO_PROJECT_TASKS: ClientProjectTask[] = [
  {
    id: "tsk-2024-01",
    type: "cliente",
    clientId: "cli-demo-corp-01",
    clientName: "CORPORACIÓN INDUSTRIAL Y LOGÍSTICA ECUATORIANA C.A.",
    boardFlow: "isp_tecnico",
    title: "Factibilidad y Estudio de Campo - Platinum Plaza",
    description: "Inspección de ductería vertical y niveles de potencia óptica en mufa de distribución.",
    column: "completado",
    priority: "alta",
    assignedTo: "Ing. Carlos Benítez",
    assignedToId: "usr-tec-03",
    startDate: "2024-01-16",
    dueDate: "2024-01-17",
    estimatedBudget: 350.0,
    executedCost: 320.0,
    checklist: [
      { id: "chk-01", text: "Verificación de poste y caja NAP más cercana", done: true },
      { id: "chk-02", text: "Medición de potencia óptica en splitter (-18 dBm)", done: true },
      { id: "chk-03", text: "Validación de ruta de ingreso a sala de servidores", done: true },
    ],
    notesThread: [
      {
        id: "nt-1",
        authorName: "Ing. Carlos Benítez",
        authorRole: "Técnico NOC",
        content: "Factibilidad 100% aprobada. Capacidad disponible en puerto PON 3 con margen de seguridad.",
        createdAt: "2024-01-16T14:30:00Z",
      },
    ],
    notes: "Factibilidad 100% aprobada. Capacidad disponible en puerto PON 3.",
    createdAt: "2024-01-16T11:00:00Z",
    updatedAt: "2024-01-17T16:00:00Z",
  },
  {
    id: "tsk-2024-02",
    type: "cliente",
    clientId: "cli-demo-corp-01",
    clientName: "CORPORACIÓN INDUSTRIAL Y LOGÍSTICA ECUATORIANA C.A.",
    boardFlow: "isp_tecnico",
    title: "Tendido y Fusión de Fibra Óptica 2 Hilos",
    description: "Tendido de acometida dieléctrica de 150 metros y conectorización SC/APC.",
    column: "completado",
    priority: "alta",
    assignedTo: "Téc. Alex Mendoza",
    assignedToId: "usr-tec-03",
    startDate: "2024-01-18",
    dueDate: "2024-01-19",
    estimatedBudget: 620.0,
    executedCost: 590.0,
    checklist: [
      { id: "chk-04", text: "Tendido canalizado por tubería EMT", done: true },
      { id: "chk-05", text: "Fusión en ODF central y roseta óptica de cliente", done: true },
      { id: "chk-06", text: "Certificación reflectométrica OTDR", done: true },
    ],
    notesThread: [
      {
        id: "nt-2",
        authorName: "Téc. Alex Mendoza",
        authorRole: "Líder de Cuadrilla",
        content: "Atenuación certificada en 0.28 dB/km. Señal final en ONT: -18.4 dBm dentro de norma.",
        createdAt: "2024-01-19T16:00:00Z",
      },
    ],
    notes: "Atenuación certificada en 0.28 dB/km. Señal final en ONT: -18.4 dBm.",
    createdAt: "2024-01-18T08:00:00Z",
    updatedAt: "2024-01-19T17:30:00Z",
  },
  {
    id: "tsk-2024-03",
    type: "cliente",
    clientId: "cli-demo-corp-01",
    clientName: "CORPORACIÓN INDUSTRIAL Y LOGÍSTICA ECUATORIANA C.A.",
    boardFlow: "isp_tecnico",
    title: "Aprovisionamiento de Router MikroTik & ONU",
    description: "Configuración de credenciales PPPoE, IP estática 186.42.110.5 y QoS simétrico.",
    column: "completado",
    priority: "urgente",
    assignedTo: "Ing. Carlos Benítez",
    assignedToId: "usr-tec-03",
    startDate: "2024-01-20",
    dueDate: "2024-01-20",
    estimatedBudget: 480.0,
    executedCost: 480.0,
    checklist: [
      { id: "chk-07", text: "Configuración de perfil PPPoE con cola simple 500M/500M", done: true },
      { id: "chk-08", text: "Asignación de IP pública fija 186.42.110.5/28", done: true },
      { id: "chk-09", text: "Test de rendimiento RFC 2544 (latencia < 4ms)", done: true },
    ],
    notesThread: [
      {
        id: "nt-3",
        authorName: "Ing. Carlos Benítez",
        authorRole: "Técnico NOC",
        content: "Enlace activado y sincronizado con NOC Central. Pruebas de velocidad dieron 502 Mbps simétricos.",
        createdAt: "2024-01-20T12:45:00Z",
      },
    ],
    notes: "Enlace activado y sincronizado con NOC Central.",
    createdAt: "2024-01-20T09:00:00Z",
    updatedAt: "2024-01-20T13:00:00Z",
  },
  {
    id: "tsk-2024-04",
    type: "cliente",
    clientId: "cli-demo-corp-01",
    clientName: "CORPORACIÓN INDUSTRIAL Y LOGÍSTICA ECUATORIANA C.A.",
    boardFlow: "isp_tecnico",
    title: "Monitoreo Preventivo de Latencia y Calidad de Enlace",
    description: "Validación de parámetros de disponibilidad exigidos por ARCOTEL.",
    column: "pruebas_homologacion",
    priority: "media",
    assignedTo: "Ing. Carlos Benítez",
    assignedToId: "usr-tec-03",
    startDate: "2026-08-01",
    dueDate: "2026-10-01",
    estimatedBudget: 200.0,
    executedCost: 85.0,
    checklist: [
      { id: "chk-10", text: "Monitoreo ICMP en Zabbix / Grafana", done: true },
      { id: "chk-11", text: "Comprobación de pérdida de paquetes 0.00%", done: true },
      { id: "chk-12", text: "Auditoría de retención de logs de tráfico IP", done: false },
    ],
    notesThread: [
      {
        id: "nt-4",
        authorName: "Ing. Carlos Benítez",
        authorRole: "Técnico NOC",
        content: "SLA garantizado del 99.8%. Rendimiento impecable durante los últimos 30 días.",
        createdAt: "2026-09-18T10:00:00Z",
      },
    ],
    notes: "SLA garantizado del 99.8%. Rendimiento impecable durante los últimos 30 días.",
    createdAt: "2026-08-01T08:00:00Z",
    updatedAt: "2026-09-18T12:00:00Z",
  },
  {
    id: "tsk-infra-01",
    type: "infraestructura_interna",
    nodeId: "nodo-demo-01",
    nodeName: "POP 01 - Telepuerto Quito Norte",
    boardFlow: "isp_tecnico",
    title: "Expansión Anillo de Fibra Óptica Troncal 10G",
    description: "Tendido e interconexión de cable ADSS de 48 hilos entre POP Norte y Nodo La Carolina.",
    column: "tendido_fibra",
    priority: "alta",
    assignedTo: "Téc. Alex Mendoza",
    assignedToId: "usr-tec-03",
    startDate: "2026-09-20",
    dueDate: "2026-10-15",
    estimatedBudget: 3400.0,
    executedCost: 1850.0,
    checklist: [
      { id: "chk-inf-1", text: "Permisos de canalización municipal y postes CNEL", done: true },
      { id: "chk-inf-2", text: "Despliegue de 1.8km de cable ADSS G.652D", done: true },
      { id: "chk-inf-3", text: "Fusión de bandejas en ODF de alta densidad", done: false },
      { id: "chk-inf-4", text: "Prueba de reflectometría bidireccional y dispersión", done: false },
    ],
    notesThread: [
      {
        id: "nt-5",
        authorName: "Téc. Alex Mendoza",
        authorRole: "Líder de Cuadrilla",
        content: "Permisos aprobados. Se avanzó con el tendido de 1.2km en la primera jornada sin novedades.",
        createdAt: "2026-09-22T17:00:00Z",
      },
    ],
    notes: "Obra estratégica para redundancia de Core de red.",
    createdAt: "2026-09-20T08:00:00Z",
    updatedAt: "2026-09-23T11:00:00Z",
  },
  {
    id: "tsk-infra-02",
    type: "infraestructura_interna",
    nodeId: "nodo-demo-01",
    nodeName: "POP 01 - Telepuerto Quito Norte",
    boardFlow: "general",
    title: "Upgrade de Sistema de Energía Ininterrumpida (UPS & Banco de Baterías)",
    description: "Reemplazo de banco de baterías de litio 48V y mantenimiento preventivo de generador Diésel.",
    column: "en_progreso",
    priority: "urgente",
    assignedTo: "Ing. Carlos Benítez",
    assignedToId: "usr-tec-03",
    startDate: "2026-09-22",
    dueDate: "2026-09-28",
    estimatedBudget: 2800.0,
    executedCost: 2450.0,
    checklist: [
      { id: "chk-bat-1", text: "Recepción e inspección física de celdas LiFePO4", done: true },
      { id: "chk-bat-2", text: "Instalación en rack y cableado con protecciones DC", done: true },
      { id: "chk-bat-3", text: "Simulación de corte de energía pública (test de carga 4h)", done: false },
      { id: "chk-bat-4", text: "Configuración de alarmas SNMP en NMS", done: false },
    ],
    notesThread: [
      {
        id: "nt-6",
        authorName: "Ing. Carlos Benítez",
        authorRole: "Técnico NOC",
        content: "Baterías instaladas con éxito. Pendiente test de descarga programado en ventana de mantenimiento nocturna.",
        createdAt: "2026-09-23T15:20:00Z",
      },
    ],
    notes: "Ventana de mantenimiento programada entre 01:00 y 04:00 AM.",
    createdAt: "2026-09-21T09:30:00Z",
    updatedAt: "2026-09-24T08:00:00Z",
  },
  {
    id: "tsk-gen-01",
    type: "cliente",
    clientId: "cli-demo-corp-01",
    clientName: "CORPORACIÓN INDUSTRIAL Y LOGÍSTICA ECUATORIANA C.A.",
    boardFlow: "general",
    title: "Auditoría Semestral de Seguridad y Penetration Testing",
    description: "Revisión de puertos abiertos, reglas de firewall perimetral y mitigación DDoS en router de cliente.",
    column: "por_iniciar",
    priority: "media",
    assignedTo: "Ing. Mauricio González",
    assignedToId: "usr-admin-01",
    startDate: "2026-10-05",
    dueDate: "2026-10-20",
    estimatedBudget: 1200.0,
    executedCost: 0.0,
    checklist: [
      { id: "chk-sec-1", text: "Escaneo Nmap y Nessus sobre bloques IP autorizados", done: false },
      { id: "chk-sec-2", text: "Revisión de políticas de filtrado RAW y FastTrack", done: false },
      { id: "chk-sec-3", text: "Elaboración de informe ejecutivo de ciberseguridad", done: false },
    ],
    notesThread: [],
    notes: "Compromiso contractual de auditoría técnica semestral.",
    createdAt: "2026-09-24T10:00:00Z",
    updatedAt: "2026-09-24T10:00:00Z",
  },
];

export const DEMO_CONTRACT: ClientContractInfo = {
  id: "con-2024-001",
  clientId: "cli-demo-corp-01",
  contractNumber: "INNTEL-SAI-2024-0412",
  arcotelHomologationCode: "ARCOTEL-CPO-2023-0981",
  planName: "Fibra Óptica Dedicado 500M Simétrico",
  signedDate: "2024-01-20",
  expirationDate: "2026-01-20",
  renewalDate: "2026-01-05",
  status: "vigente",
  monthlyPrice: 95.0,
  notes: "Contrato homologado por ARCOTEL bajo el Régimen General de Telecomunicaciones SAI. Cláusula de SLA 99.8% de disponibilidad.",
};

export const DEMO_CLIENT_VAULT_ITEMS: ClientVaultItem[] = [
  {
    id: "vlt-cli-01",
    clientId: "cli-demo-corp-01",
    serviceName: "Router de Borde MikroTik Platinum Plaza",
    category: "ont_router",
    username: "admin_inntel",
    encryptedPassword: simpleEncrypt("MikroTik#Corp2026"),
    ipAddress: "186.42.110.5",
    port: 8291,
    notes: "Winbox port 8291 protegido por Firewall filter rules. Solo accesible desde IP NOC INNTEL.",
    updatedAt: "2024-01-20T14:00:00Z",
  },
  {
    id: "vlt-cli-02",
    clientId: "cli-demo-corp-01",
    serviceName: "Red Wi-Fi 6 Corporativa (SSID: CorpEcuador_5G)",
    category: "wifi",
    username: "WPA3-Enterprise",
    encryptedPassword: simpleEncrypt("WiFi#Corp2026*Secure"),
    notes: "Red con aislamiento de clientes (AP Isolation) y ancho de canal 80MHz.",
    updatedAt: "2024-01-20T14:00:00Z",
  },
  {
    id: "vlt-cli-03",
    clientId: "cli-demo-corp-01",
    serviceName: "Túnel de Acceso PPPoE / Radius",
    category: "pppoe",
    username: "corpecuador_corp",
    encryptedPassword: simpleEncrypt("CorpSecurePppoe2026*"),
    notes: "Autenticación Radius centralizada con asignación de IP estática.",
    updatedAt: "2024-01-20T14:00:00Z",
  },
];

export const DEMO_TICKETS: Ticket[] = [
  {
    id: "tkt-2024-01",
    ticketNumber: "TKT-8901",
    clientId: "cli-demo-corp-01",
    clientName: "CORPORACIÓN INDUSTRIAL Y LOGÍSTICA ECUATORIANA C.A.",
    title: "Instalación, Fusión y Certificación de Enlace Dedicado 500M",
    description: "Instalación de acometida de fibra óptica desde el splitter 1:8 de Platinum Plaza hasta rack de servidores en piso 8.",
    category: "configuracion_ip",
    priority: "alta",
    status: "resuelto",
    assignedToId: "usr-tec-03",
    assignedToName: "Ing. Carlos Benítez",
    createdAt: "2024-01-20T08:30:00Z",
    resolvedAt: "2024-01-20T14:15:00Z",
    resolutionNotes: "Fusión realizada con 0.02 dB de pérdida en 1310/1550nm. Potencia óptica recibida: -18.4 dBm. Enlace 100% operativo con 500 Mbps simétricos comprobados.",
    nodeName: "POP 01 - Telepuerto Quito Norte (MikroTik CCR2004)",
  },
];

export const DEMO_MONTHLY_CHARGES: MonthlyCharge[] = [
  {
    id: "chg-2024-08",
    clientId: "cli-demo-corp-01",
    clientName: "CORPORACIÓN INDUSTRIAL Y LOGÍSTICA ECUATORIANA C.A.",
    clientRuc: "1792345678001",
    month: 8,
    year: 2026,
    serviceDescription: "Servicio de Internet Dedicado Simétrico 500M - Agosto 2026",
    subtotal: 95.0,
    ivaAmount: 14.25,
    total: 109.25,
    status: "pagado",
    paymentDate: "2026-08-05T11:20:00Z",
    paymentMethod: "Transferencia Banco Pichincha",
    invoiceNumber: "001-010-0004521",
  },
  {
    id: "chg-2024-09",
    clientId: "cli-demo-corp-01",
    clientName: "CORPORACIÓN INDUSTRIAL Y LOGÍSTICA ECUATORIANA C.A.",
    clientRuc: "1792345678001",
    month: 9,
    year: 2026,
    serviceDescription: "Servicio de Internet Dedicado Simétrico 500M - Septiembre 2026",
    subtotal: 95.0,
    ivaAmount: 14.25,
    total: 109.25,
    status: "pendiente",
    invoiceNumber: "001-010-0004780",
  },
];

export const DEMO_POLICIES: ArcotelPolicy[] = [
  {
    id: "pol-arcotel-01",
    policyNumber: "POL-SEG-2026-00452",
    insuranceCompany: "Seguros Sucre / Seguros del Pichincha",
    policyType: "fiel_cumplimiento",
    titleGrantCode: "CON-INNTEL-SAI-2018-04",
    startDate: "2024-01-01",
    expirationDate: "2026-12-31",
    insuredAmount: 25000.0,
    status: "vigente",
    daysUntilExpiration: 280,
    notes: "Póliza de fiel cumplimiento del contrato de concesión del Servicio de Acceso a Internet (SAI) otorgado por ARCOTEL.",
  },
];

export const DEMO_VAULT: VaultCredential[] = [
  {
    id: "vlt-gen-01",
    serviceName: "Portal SIETEL - Carga Mensual ARCOTEL",
    serviceType: "sietel",
    portalUrl: "https://sietel.arcotel.gob.ec/",
    username: "INNTEL_CORP_RUC1793211553001",
    encryptedPassword: simpleEncrypt("Arcotel#Sietel2026*"),
    notes: "Acceso institucional para reporte de abonados, capacidad de tráfico internacional y calidad de servicio.",
    allowedRoles: ["superadmin", "admin", "legal"],
    updatedAt: "2024-01-01T08:00:00Z",
  },
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: "log-demo-01",
    userId: "usr-admin-01",
    userEmail: "admin@inntelcorp.com",
    userRole: "admin",
    action: "CREATE_CLIENT",
    resource: "CORPORACIÓN INDUSTRIAL Y LOGÍSTICA ECUATORIANA C.A.",
    details: "Alta de nuevo cliente corporativo RUC: 1792345678001 en Telepuerto Quito Norte.",
    timestamp: "2024-01-15T08:30:00Z",
  },
  {
    id: "log-demo-02",
    userId: "usr-tec-03",
    userEmail: "tecnico@inntelcorp.com",
    userRole: "tecnico",
    action: "UPDATE_VAULT",
    resource: "Router de Borde MikroTik Platinum Plaza",
    details: "Almacenamiento cifrado de credenciales de acceso Winbox y PPPoE.",
    timestamp: "2024-01-20T14:05:00Z",
  },
  {
    id: "log-demo-03",
    userId: "usr-leg-05",
    userEmail: "legal@inntelcorp.com",
    userRole: "legal",
    action: "GENERATE_DOC",
    resource: "Contrato INNTEL-SAI-2024-0412",
    details: "Generación y archivo de contrato homologado ARCOTEL con cláusula de SLA 99.8%.",
    timestamp: "2024-01-20T15:00:00Z",
  },
  {
    id: "log-demo-04",
    userId: "usr-fin-02",
    userEmail: "finanzas@inntelcorp.com",
    userRole: "finanzas",
    action: "EXPORT_FINANCE",
    resource: "Factura 001-010-0004521",
    details: "Emisión de comprobante mensual de cobro por $109.25 (Plan 500M + IVA).",
    timestamp: "2026-08-05T11:25:00Z",
  },
];

export const INITIAL_CONCESSION_INFO: ArcotelConcessionInfo = {
  titleName: "Permiso Único para Prestación de Servicios del Régimen General de Telecomunicaciones",
  titleDate: "2020-08-15",
  concessionaireCode: "CON-SVA-2024-089",
  lastPolicyDate: "2026-06-15",
  reminderDays: 30,
  websiteUrl: "https://www.inntelcorp.com",
  additionalFields: [
    { id: "f-1", label: "Número de Trámite Quipux", value: "ARCOTEL-CZT4-2026-0422-M" },
    { id: "f-2", label: "Resolución ARCOTEL Matriz", value: "ARCOTEL-2020-0582-R" },
  ],
};

export const INITIAL_ARCOTEL_FILES: ArcotelPeriodicFile[] = [
  {
    id: "arc-lopam-01",
    subsystem: "sietel_lopam",
    fileName: "SIETEL_LOPAM_Semana38_2026.xlsx",
    fileSize: "1.4 MB",
    period: "Semana 38 - 2026",
    uploadedAt: "2026-09-18T09:30:00Z",
    uploadedBy: "Abg. Fernando Viteri",
    fileType: "xlsx",
    status: "vigente",
    notes: "Reporte de Líneas Operativas y Abonados última semana.",
  },
  {
    id: "arc-tar-01",
    subsystem: "sietel_tarifas",
    fileName: "Matriz_Tarifaria_Homologada_Septiembre2026.pdf",
    fileSize: "840 KB",
    period: "Septiembre 2026",
    uploadedAt: "2026-09-01T10:00:00Z",
    uploadedBy: "Abg. Fernando Viteri",
    fileType: "pdf",
    status: "enviado",
    notes: "Tarifas registradas ante ARCOTEL para planes residenciales y corporativos.",
  },
  {
    id: "arc-usr-01",
    subsystem: "sietel_usuarios",
    fileName: "Reporte_Abonados_Activos_Agosto2026.xlsx",
    fileSize: "2.1 MB",
    period: "Agosto 2026",
    uploadedAt: "2026-09-05T11:15:00Z",
    uploadedBy: "Abg. Fernando Viteri",
    fileType: "xlsx",
    status: "enviado",
  },
  {
    id: "arc-cal-01",
    subsystem: "sietel_calidad",
    fileName: "Parametros_Calidad_Servicio_QoS_Agosto2026.pdf",
    fileSize: "1.8 MB",
    period: "Agosto 2026",
    uploadedAt: "2026-09-10T16:00:00Z",
    uploadedBy: "Ing. Mauricio González",
    fileType: "pdf",
    status: "enviado",
    notes: "Disponibilidad de red 99.92%, latencia promedio 14ms.",
  },
  {
    id: "arc-enc-01",
    subsystem: "sietel_encuestas",
    fileName: "Resultados_Encuesta_Satisfaccion_2026_S1.pdf",
    fileSize: "3.2 MB",
    period: "Primer Semestre 2026",
    uploadedAt: "2026-07-15T12:00:00Z",
    uploadedBy: "Abg. Fernando Viteri",
    fileType: "pdf",
    status: "enviado",
  },
  {
    id: "arc-cap-01",
    subsystem: "sietel_capacidades",
    fileName: "Capacidad_Internacional_Transito_Agosto2026.xlsx",
    fileSize: "920 KB",
    period: "Agosto 2026",
    uploadedAt: "2026-09-02T14:30:00Z",
    uploadedBy: "Ing. Mauricio González",
    fileType: "xlsx",
    status: "enviado",
  },
  {
    id: "arc-fod-01",
    subsystem: "fodetel",
    fileName: "Declaracion_Trimestral_FODETEL_2026_Q2.xlsx",
    fileSize: "1.1 MB",
    period: "Trimestre II - 2026",
    uploadedAt: "2026-07-20T10:45:00Z",
    uploadedBy: "Lic. Carlos Mendoza",
    fileType: "xlsx",
    status: "enviado",
    notes: "Aporte del 1% a FODETEL con comprobante de depósito bancario adjunto.",
  },
  {
    id: "arc-fod-02",
    subsystem: "fodetel",
    fileName: "Comprobante_Pago_FODETEL_Q2_2026.pdf",
    fileSize: "450 KB",
    period: "Trimestre II - 2026",
    uploadedAt: "2026-07-20T10:50:00Z",
    uploadedBy: "Lic. Carlos Mendoza",
    fileType: "pdf",
    status: "enviado",
  },
  {
    id: "arc-cnt-01",
    subsystem: "contingencia",
    fileName: "Plan_Continuidad_Operativa_Red_2026.docx",
    fileSize: "4.5 MB",
    period: "Vigencia Anual 2026",
    uploadedAt: "2026-01-10T09:00:00Z",
    uploadedBy: "Ing. Mauricio González",
    fileType: "docx",
    status: "vigente",
    notes: "Plan de Contingencia ante cortes submarinos y desastres.",
  },
  {
    id: "arc-bdh-01",
    subsystem: "bdh",
    fileName: "Cruce_Base_Beneficiarios_BDH_Q3_2026.xlsx",
    fileSize: "780 KB",
    period: "Tercer Trimestre 2026",
    uploadedAt: "2026-08-20T15:20:00Z",
    uploadedBy: "Lic. Carlos Mendoza",
    fileType: "xlsx",
    status: "vigente",
    notes: "Nómina de abonados beneficiarios de tarifa social.",
  },
];

export const INITIAL_CLIENT_DOCUMENTS: ClientDocumentFile[] = [
  {
    id: "doc-cli-01",
    clientId: "cli-demo-corp-01",
    title: "Contrato de Adhesión SAI ARCOTEL Firmado",
    documentType: "contrato_adhesion",
    fileName: "Contrato_Firmado_INNTEL-SAI-2024-0412.pdf",
    fileSize: "1.9 MB",
    uploadedAt: "2024-01-20T16:00:00Z",
  },
  {
    id: "doc-cli-02",
    clientId: "cli-demo-corp-01",
    title: "Autorización de Protección de Datos Personales",
    documentType: "proteccion_datos",
    fileName: "Consentimiento_Datos_Personales_Corpecuador.pdf",
    fileSize: "620 KB",
    uploadedAt: "2024-01-20T16:05:00Z",
  },
  {
    id: "doc-cli-03",
    clientId: "cli-demo-corp-01",
    title: "Nombramiento Representante Legal & RUC",
    documentType: "cedula_ruc",
    fileName: "Nombramiento_Patricio_Echeverria.pdf",
    fileSize: "1.2 MB",
    uploadedAt: "2024-01-15T09:00:00Z",
  },
  {
    id: "doc-cli-04",
    clientId: "cli-demo-corp-01",
    title: "Acta de Entrega-Recepción de Equipos ONT / Router",
    documentType: "acta_entrega",
    fileName: "Acta_Entrega_ONT_HWTCD928B104.pdf",
    fileSize: "850 KB",
    uploadedAt: "2024-01-20T17:30:00Z",
  },
];

// Exportaciones iniciales para el estado de la aplicación
export const INITIAL_NODES: NodeLocation[] = [DEMO_NODE, DEMO_NODE_2];
export const INITIAL_IP_POOLS: IpPool[] = [DEMO_IP_POOL];
export const INITIAL_CLIENTS: Client[] = [DEMO_CLIENT];
export const INITIAL_CLIENT_SERVICES: ClientService[] = [DEMO_CLIENT_SERVICE];
export const INITIAL_POLICIES: ArcotelPolicy[] = DEMO_POLICIES;
export const INITIAL_VAULT: VaultCredential[] = DEMO_VAULT;
export const INITIAL_TICKETS: Ticket[] = DEMO_TICKETS;
export const INITIAL_EXPENSES: Expense[] = [];
export const INITIAL_MONTHLY_CHARGES: MonthlyCharge[] = DEMO_MONTHLY_CHARGES;
export const INITIAL_PROJECT_TASKS: ClientProjectTask[] = DEMO_PROJECT_TASKS;
export const INITIAL_QUOTES: ClientQuoteOrder[] = [DEMO_QUOTE_ORDER];
export const INITIAL_CLIENT_VAULT: ClientVaultItem[] = DEMO_CLIENT_VAULT_ITEMS;
export const INITIAL_CONTRACTS: ClientContractInfo[] = [DEMO_CONTRACT];
export const INITIAL_AUDIT_LOGS: AuditLog[] = DEMO_AUDIT_LOGS;

// ==========================================
// MÓDULO DE CONTROL DE INVENTARIOS Y BODEGAS
// ==========================================

export const INITIAL_CATEGORIES: ProductCategory[] = [
  {
    id: "cat-red-ont",
    name: "Equipos de Red & ONTs",
    description: "Terminales de red óptica (ONT), routers inalámbricos y switches gigabit",
    itemType: "producto",
    createdAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "cat-fibra-pasivos",
    name: "Fibra Óptica & Pasivos",
    description: "Cables troncales, cables drop, splitters balanceados y cajas NAP",
    itemType: "producto",
    createdAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "cat-cables-conec",
    name: "Conectividad & Herrajes",
    description: "Conectores SC/APC, patch cords, pigtails, tensores y flejes de acero",
    itemType: "producto",
    createdAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "cat-herramientas",
    name: "Herramientas de Planta Externa",
    description: "Fusionadoras, cortadoras de precisión, power meters y OTDRs",
    itemType: "producto",
    createdAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "cat-servicios-tec",
    name: "Servicios Técnicos & Despliegue",
    description: "Mano de obra especializada, acometidas de fibra, fusiones y enlaces de datos",
    itemType: "servicio",
    createdAt: "2024-01-01T08:00:00Z",
  },
];

export const INITIAL_BRANDS: ProductBrand[] = [
  { id: "brd-huawei", name: "Huawei", originCountry: "China", createdAt: "2024-01-01T08:00:00Z" },
  { id: "brd-mikrotik", name: "MikroTik", originCountry: "Letonia", createdAt: "2024-01-01T08:00:00Z" },
  { id: "brd-ubiquiti", name: "Ubiquiti Networks", originCountry: "EE.UU.", createdAt: "2024-01-01T08:00:00Z" },
  { id: "brd-fiberhome", name: "FiberHome", originCountry: "China", createdAt: "2024-01-01T08:00:00Z" },
  { id: "brd-furukawa", name: "Furukawa Electric", originCountry: "Japón/Brasil", createdAt: "2024-01-01T08:00:00Z" },
  { id: "brd-zte", name: "ZTE Corporation", originCountry: "China", createdAt: "2024-01-01T08:00:00Z" },
  { id: "brd-inntel", name: "INNTEL CORP", originCountry: "Ecuador", createdAt: "2024-01-01T08:00:00Z" },
];

export const INITIAL_WAREHOUSES: Warehouse[] = [
  {
    id: "wh-central",
    code: "BOD-CENTRAL",
    name: "Bodega Central - Quito (NOC)",
    address: "Av. Amazonas N45-12 y Gaspar de Villarroel",
    city: "Quito, Pichincha",
    responsibleName: "Ing. Diego Cárdenas",
    responsiblePhone: "+593 99 111 2233",
    isDefault: true,
    status: "activo",
    createdAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "wh-gye",
    code: "BOD-GYE",
    name: "Bodega Regional - Guayaquil",
    address: "Av. 9 de Octubre y Malecón Simón Bolívar",
    city: "Guayaquil, Guayas",
    responsibleName: "Ing. Carlos Mendoza",
    responsiblePhone: "+593 98 444 5566",
    isDefault: false,
    status: "activo",
    createdAt: "2024-01-05T08:00:00Z",
  },
  {
    id: "wh-movil-01",
    code: "BOD-MOV-01",
    name: "Bodega Móvil Técnico 1 (Cuadrilla)",
    address: "Vehículo Móvil Hino - Móvil 04",
    city: "Quito Norte",
    responsibleName: "Téc. Roberto Gómez",
    responsiblePhone: "+593 97 123 4567",
    isDefault: false,
    status: "activo",
    createdAt: "2024-01-10T08:00:00Z",
  },
];

export const INITIAL_PRODUCTS: InventoryProduct[] = [
  {
    id: "prod-ont-hw-eg8145v5",
    sku: "ONT-HW-EG8145V5",
    barcode: "786100120001",
    name: "ONT Huawei EchoLife EG8145V5 Dual Band AC GPON",
    description: "Terminal GPON con 4 puertos GE, 1 puerto POTS, 1 USB y Wi-Fi Dual Band 2.4/5GHz (MIMO 2x2)",
    type: "producto",
    categoryId: "cat-red-ont",
    categoryName: "Equipos de Red & ONTs",
    brandId: "brd-huawei",
    brandName: "Huawei",
    unit: "unidad",
    baseCost: 35.0,
    salePrice: 65.0,
    salePriceConIva: 74.75,
    taxMode: "EXCLUIDO",
    ivaRate: 15,
    tracksStock: true,
    stock: 45,
    minStock: 10,
    maxStock: 150,
    stockByWarehouse: {
      "wh-central": 35,
      "wh-gye": 8,
      "wh-movil-01": 2,
    },
    defaultWarehouseId: "wh-central",
    model: "EG8145V5",
    serialNumberRequired: true,
    status: "activo",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-10T09:00:00Z",
  },
  {
    id: "prod-mtk-hex-rb750gr3",
    sku: "RTR-MTK-HEX-GR3",
    barcode: "786100120002",
    name: "Router MikroTik hEX RB750Gr3 5xGigabit RouterOS L4",
    description: "Routerboard Gigabit de 5 puertos Ethernet 10/100/1000 con CPU dual-core 880MHz y soporte IPsec acelerado por hardware",
    type: "producto",
    categoryId: "cat-red-ont",
    categoryName: "Equipos de Red & ONTs",
    brandId: "brd-mikrotik",
    brandName: "MikroTik",
    unit: "unidad",
    baseCost: 48.0,
    salePrice: 85.0,
    salePriceConIva: 97.75,
    taxMode: "EXCLUIDO",
    ivaRate: 15,
    tracksStock: true,
    stock: 24,
    minStock: 6,
    maxStock: 50,
    stockByWarehouse: {
      "wh-central": 18,
      "wh-gye": 5,
      "wh-movil-01": 1,
    },
    defaultWarehouseId: "wh-central",
    model: "RB750Gr3",
    serialNumberRequired: true,
    status: "activo",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-10T09:00:00Z",
  },
  {
    id: "prod-fib-drop-1h-1000",
    sku: "FIB-DROP-1H-1000M",
    barcode: "786100120003",
    name: "Bobina Cable Drop Fibra Óptica 1 Hilo G.657.A2 (1000 Metros)",
    description: "Cable de acometida FTTH autosoportado figura 8 con mensajero de acero y cubierta LSZH ignífuga",
    type: "producto",
    categoryId: "cat-fibra-pasivos",
    categoryName: "Fibra Óptica & Pasivos",
    brandId: "brd-furukawa",
    brandName: "Furukawa Electric",
    unit: "rollo",
    baseCost: 75.0,
    salePrice: 120.0,
    salePriceConIva: 138.0,
    taxMode: "EXCLUIDO",
    ivaRate: 15,
    tracksStock: true,
    stock: 12,
    minStock: 3,
    maxStock: 30,
    stockByWarehouse: {
      "wh-central": 9,
      "wh-gye": 2,
      "wh-movil-01": 1,
    },
    defaultWarehouseId: "wh-central",
    fiberLengthMeters: 1000,
    status: "activo",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-10T09:00:00Z",
  },
  {
    id: "prod-con-scapc-box",
    sku: "CON-SCAPC-100U",
    barcode: "786100120004",
    name: "Conectores Rápidos Ensamblaje en Campo SC/APC (Caja 100u)",
    description: "Conector mecánico prepulido para fibra monomodo 0.25/0.9/2.0/3.0mm, pérdida de inserción <= 0.3dB",
    type: "producto",
    categoryId: "cat-cables-conec",
    categoryName: "Conectividad & Herrajes",
    brandId: "brd-fiberhome",
    brandName: "FiberHome",
    unit: "caja",
    baseCost: 22.0,
    salePrice: 45.0,
    salePriceConIva: 51.75,
    taxMode: "EXCLUIDO",
    ivaRate: 15,
    tracksStock: true,
    stock: 30,
    minStock: 5,
    maxStock: 80,
    stockByWarehouse: {
      "wh-central": 22,
      "wh-gye": 5,
      "wh-movil-01": 3,
    },
    defaultWarehouseId: "wh-central",
    status: "activo",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-10T09:00:00Z",
  },
  {
    id: "prod-spl-plc-1x8",
    sku: "SPL-PLC-1X8-SCAPC",
    barcode: "786100120005",
    name: "Splitter Óptico PLC Balanceado 1x8 Conectorizado SC/APC",
    description: "Divisor óptico planar mono-modo 1260-1650nm para cajas NAP y distribución de segundo nivel en red FTTH",
    type: "producto",
    categoryId: "cat-fibra-pasivos",
    categoryName: "Fibra Óptica & Pasivos",
    brandId: "brd-fiberhome",
    brandName: "FiberHome",
    unit: "unidad",
    baseCost: 4.5,
    salePrice: 9.5,
    salePriceConIva: 10.93,
    taxMode: "EXCLUIDO",
    ivaRate: 15,
    tracksStock: true,
    stock: 60,
    minStock: 15,
    maxStock: 200,
    stockByWarehouse: {
      "wh-central": 45,
      "wh-gye": 10,
      "wh-movil-01": 5,
    },
    defaultWarehouseId: "wh-central",
    status: "activo",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-10T09:00:00Z",
  },
  {
    id: "srv-inst-acometida-ftth",
    sku: "SRV-INST-FTTH",
    name: "Instalación y Tendido de Acometida de Fibra Óptica FTTH",
    description: "Mano de obra para tendido de hasta 200 metros de cable drop, conectorización en NAP y roseta interna",
    type: "servicio",
    categoryId: "cat-servicios-tec",
    categoryName: "Servicios Técnicos & Despliegue",
    brandId: "brd-inntel",
    brandName: "INNTEL CORP",
    unit: "servicio",
    baseCost: 15.0,
    salePrice: 35.0,
    salePriceConIva: 40.25,
    taxMode: "EXCLUIDO",
    ivaRate: 15,
    tracksStock: false,
    stock: 0,
    minStock: 0,
    stockByWarehouse: {},
    status: "activo",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-10T09:00:00Z",
  },
  {
    id: "srv-fusion-fibra-punto",
    sku: "SRV-FUS-PUNTO",
    name: "Fusión por Arco Voltáico y Certificación Óptica (por hilo)",
    description: "Servicio de empalme por fusión óptica en ODF/Manga y medición con OTDR calibrado",
    type: "servicio",
    categoryId: "cat-servicios-tec",
    categoryName: "Servicios Técnicos & Despliegue",
    brandId: "brd-inntel",
    brandName: "INNTEL CORP",
    unit: "servicio",
    baseCost: 8.0,
    salePrice: 18.0,
    salePriceConIva: 20.7,
    taxMode: "EXCLUIDO",
    ivaRate: 15,
    tracksStock: false,
    stock: 0,
    minStock: 0,
    stockByWarehouse: {},
    status: "activo",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-10T09:00:00Z",
  },
  {
    id: "srv-soporte-especializado-noc",
    sku: "SRV-SOP-NOC",
    name: "Soporte Técnico de Red & Configuración BGP/OLT (Hora Técnica)",
    description: "Asistencia de ingeniería Nivel 3 para ruteo avanzado, VLANs de servicios y aprovisionamiento OLT",
    type: "servicio",
    categoryId: "cat-servicios-tec",
    categoryName: "Servicios Técnicos & Despliegue",
    brandId: "brd-inntel",
    brandName: "INNTEL CORP",
    unit: "hora",
    baseCost: 25.0,
    salePrice: 50.0,
    salePriceConIva: 57.5,
    taxMode: "EXCLUIDO",
    ivaRate: 15,
    tracksStock: false,
    stock: 0,
    minStock: 0,
    stockByWarehouse: {},
    status: "activo",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-10T09:00:00Z",
  },
];

export const INITIAL_KARDEX: KardexEntry[] = [
  {
    id: "kdx-001",
    date: "2024-01-10T10:00:00Z",
    productId: "prod-ont-hw-eg8145v5",
    productName: "ONT Huawei EchoLife EG8145V5 Dual Band AC GPON",
    warehouseId: "wh-central",
    warehouseName: "Bodega Central - Quito (NOC)",
    type: "PURCHASE_RECEIPT",
    referenceId: "CMP-2024-001",
    referenceDocNumber: "FAC-001-002-00004510",
    concept: "Ingreso inicial de inventario - Importación Lote ONTs",
    entryQuantity: 40,
    entryUnitCost: 35.0,
    entryTotalCost: 1400.0,
    balanceQuantity: 40,
    balanceAverageCost: 35.0,
    balanceTotalCost: 1400.0,
    userName: "Ing. Diego Cárdenas",
    createdAt: "2024-01-10T10:00:00Z",
  },
  {
    id: "kdx-002",
    date: "2024-01-12T14:30:00Z",
    productId: "prod-ont-hw-eg8145v5",
    productName: "ONT Huawei EchoLife EG8145V5 Dual Band AC GPON",
    warehouseId: "wh-central",
    warehouseName: "Bodega Central - Quito (NOC)",
    type: "TRANSFER_OUT",
    referenceId: "TRF-2024-001",
    referenceDocNumber: "TRF-2024-001",
    concept: "Traslado de 5 ONTs hacia Bodega Zonal Guayaquil",
    exitQuantity: 5,
    exitUnitCost: 35.0,
    exitTotalCost: 175.0,
    balanceQuantity: 35,
    balanceAverageCost: 35.0,
    balanceTotalCost: 1225.0,
    userName: "Ing. Diego Cárdenas",
    createdAt: "2024-01-12T14:30:00Z",
  },
  {
    id: "kdx-003",
    date: "2024-01-12T14:30:00Z",
    productId: "prod-ont-hw-eg8145v5",
    productName: "ONT Huawei EchoLife EG8145V5 Dual Band AC GPON",
    warehouseId: "wh-gye",
    warehouseName: "Bodega Regional - Guayaquil",
    type: "TRANSFER_IN",
    referenceId: "TRF-2024-001",
    referenceDocNumber: "TRF-2024-001",
    concept: "Recepción de traslado desde Bodega Central Quito",
    entryQuantity: 5,
    entryUnitCost: 35.0,
    entryTotalCost: 175.0,
    balanceQuantity: 8,
    balanceAverageCost: 35.0,
    balanceTotalCost: 280.0,
    userName: "Ing. Carlos Mendoza",
    createdAt: "2024-01-12T14:30:00Z",
  },
  {
    id: "kdx-004",
    date: "2024-01-15T09:15:00Z",
    productId: "prod-mtk-hex-rb750gr3",
    productName: "Router MikroTik hEX RB750Gr3 5xGigabit RouterOS L4",
    warehouseId: "wh-central",
    warehouseName: "Bodega Central - Quito (NOC)",
    type: "PURCHASE_RECEIPT",
    referenceId: "CMP-2024-002",
    referenceDocNumber: "FAC-002-001-00012890",
    concept: "Adquisición routers para clientes corporativos",
    entryQuantity: 20,
    entryUnitCost: 48.0,
    entryTotalCost: 960.0,
    balanceQuantity: 20,
    balanceAverageCost: 48.0,
    balanceTotalCost: 960.0,
    userName: "Ing. Diego Cárdenas",
    createdAt: "2024-01-15T09:15:00Z",
  },
];

export const INITIAL_TRANSFERS: WarehouseTransfer[] = [
  {
    id: "trf-2024-001",
    transferNumber: "TRF-2024-001",
    date: "2024-01-12T14:30:00Z",
    originWarehouseId: "wh-central",
    originWarehouseName: "Bodega Central - Quito (NOC)",
    destWarehouseId: "wh-gye",
    destWarehouseName: "Bodega Regional - Guayaquil",
    productId: "prod-ont-hw-eg8145v5",
    productName: "ONT Huawei EchoLife EG8145V5 Dual Band AC GPON",
    quantity: 5,
    unitCost: 35.0,
    totalCost: 175.0,
    reason: "Abastecimiento de stock para nuevas instalaciones en Guayaquil",
    responsibleUser: "Ing. Diego Cárdenas",
    status: "completada",
    createdAt: "2024-01-12T14:30:00Z",
  },
];

export const INITIAL_ADJUSTMENTS: InventoryAdjustment[] = [
  {
    id: "adj-2024-001",
    adjustmentNumber: "ADJ-2024-001",
    date: "2024-01-10T08:30:00Z",
    type: "manual_ingreso",
    warehouseId: "wh-central",
    warehouseName: "Bodega Central - Quito (NOC)",
    concept: "Carga de saldo inicial tras toma física de inventario 2024",
    items: [
      {
        productId: "prod-spl-plc-1x8",
        productName: "Splitter Óptico PLC Balanceado 1x8 Conectorizado SC/APC",
        type: "ingreso",
        quantity: 45,
        unitCost: 4.5,
        previousStock: 0,
        newStock: 45,
      },
    ],
    responsibleUser: "Ing. Diego Cárdenas",
    createdAt: "2024-01-10T08:30:00Z",
  },
];
