/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        lumina: {
          surface: "#f8f9ff",
          "surface-dim": "#cbdbf5",
          "surface-bright": "#f8f9ff",
          "surface-container-lowest": "#ffffff",
          "surface-container-low": "#eff4ff",
          "surface-container": "#e5eeff",
          "surface-container-high": "#dce9ff",
          "surface-container-highest": "#d3e4fe",
          "on-surface": "#0b1c30",
          "on-surface-variant": "#434655",
          "inverse-surface": "#213145",
          "inverse-on-surface": "#eaf1ff",
          outline: "#737686",
          "outline-variant": "#c3c6d7",
          "surface-tint": "#0053db",
          primary: "#004ac6",
          "on-primary": "#ffffff",
          "primary-container": "#2563eb",
          "on-primary-container": "#eeefff",
          "inverse-primary": "#b4c5ff",
          secondary: "#712ae2",
          "on-secondary": "#ffffff",
          "secondary-container": "#8a4cfc",
          "on-secondary-container": "#fffbff",
          tertiary: "#4d556b",
          "on-tertiary": "#ffffff",
          "tertiary-container": "#656d84",
          "on-tertiary-container": "#eef0ff",
          error: "#EF4444",
          "on-error": "#ffffff",
          "error-container": "#ffdad6",
          "on-error-container": "#93000a",
          "surface-base": "#F1F5F9",
          "surface-card": "#FFFFFF",
          success: "#10B981",
          warning: "#F59E0B",
          border: "#E2E8F0",
        },
        inntel: {
          blue: "#004ac6",
          primary: "#2563eb",
          purple: "#712ae2",
          dark: "#0b1c30",
          cyan: "#0053db",
        },
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        "lumina-subtle": "0 1px 3px 0 rgba(15, 23, 42, 0.04), 0 1px 2px -1px rgba(15, 23, 42, 0.04)",
        "lumina-card": "0 2px 6px -1px rgba(15, 23, 42, 0.05), 0 2px 4px -2px rgba(15, 23, 42, 0.03)",
        "lumina-dropdown": "0 10px 25px -3px rgba(15, 23, 42, 0.08), 0 4px 6px -4px rgba(15, 23, 42, 0.04)",
        "lumina-focus": "0 0 0 3px rgba(37, 99, 235, 0.15)",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
      },
      spacing: {
        sidebar: "260px",
        header: "64px",
      },
    },
  },
  plugins: [],
};
